---
title: "go实现多协程之间的协作-context包" #标题
date: 2023-07-18T23:38:16+08:00 #创建时间
lastmod: 2023-07-18T23:38:16+08:00 #更新时间
author: ["citybear"] #作者
categories: # 没有分类界面可以不填写
- tech
tags: # 标签
- go并发编程
- go源码
keywords: 
- 
description: "" #描述 每个文章内容前面的展示描述
weight: # 输入1可以顶置文章，用来给文章展示排序，不填就默认按时间排序
slug: ""
draft: false # 是否为草稿
comments: true #是否展示评论 有自带的扩展成twikoo
showToc: true # 显示目录 文章侧边栏toc目录
TocOpen: true # 自动展开目录
hidemeta: false # 是否隐藏文章的元信息，如发布日期、作者等
disableShare: true # 底部不显示分享栏
showbreadcrumbs: true #顶部显示当前路径
cover:
    image: "" #图片路径：posts/tech/文章1/picture.png
    caption: "" #图片底部描述
    alt: ""
    relative: false

# reward: true # 打赏
mermaid: true #自己加的是否开启mermaid
---

**启动子协程之前都已经明确知道子协程的总量，如果不知道的话，该怎么实现呢?**

# 通过sync.WaitGroup 
- <font color="red">共享内存计数器+信号量队列阻塞和唤醒对应协程</font>
{{< innerlink src="posts/tech/go17.md" >}}

# 通过上下文 context 包 （channel传递消息）
![](context1.png)

``` go 
type Context interface {
  // [1] 返回上下文的截止时间
  Deadline() (deadline time.Time, ok bool)
  // 返回一个通道，当上下文结束时，会关闭该通道，此时 <-ctx.Done() 结束阻塞
  Done() <-chan struct{}
  // [2] 该方法会在上下文结束时返回一个not nil err，该err用于表示上下文结束的原因
  Err() error
  // 返回与key关联的上下文的value
  Value(key interface{}) interface{}
}
```

## 相关函数
- 通过 WithXXX 方法返回一个从父 Context 拷贝的新的可撤销子 Context 对象和对应撤销函数 CancelFunc
  - WithDeadline 和 WithTimeout 分别比 WithCancel 多了一个 deadline 和 timeout 时间参数，表示子 Context 存活的最长时间，如果超过了该时间，会自动撤销对应的子 Context, 通常使用时还是会主动调用 cancelFunc
  - WithValue 方法用于返回包含上下文信息的 Context 对象
- <font color="red">CancelFunc 是一个函数类型</font>，调用它时会撤销对应的子 Context 对象, <font color="red">思考主函数里为啥 defer cancelFunc()?</font>
- **<font color="red">当满足某种条件时，我们可以通过调用该函数CancelFunc结束所有子协程的运行，主协程在接收到信号后可以继续往后执行。</font>**
- ctx.Done() 方法返回一个通道，该通道会在调用 cancelFunc 函数时关闭，或者在父 context 撤销时也会被关闭。 等待阻塞用
  - 配合select多路监听，看循环是否配置default
- **Go官方建议上下文不应该嵌入到结构体中使用**，而是应该<font color="red">将上下文作为调用函数/方法的第一个参数使用，并推荐参数命名为ctx</font>

- WithoutCancel(parent Context) Context go1.21内置,当 parent 被取消时，不会波及到这个函数返回的 Context。返回一个拷贝了parent的所有值kv但是不带过期属性的context
不带cancel()，父级ctx取消不会被一起取消   


## 实战常见用处：
1. 从请求上下文中获取用户信息
2. 从请求上下文中获取请求的唯一标识（traceId，常用于分布式日志追踪）
3. 控制请求超时时间
4. 控制协程优雅结束

### 控制协程优雅结束

`ctx, cancelFunc := context.WithCancel(context.Background())`
context.Background() 方法返回父 Context，**该 Context 没有值，永远不会取消，可以看作是所有 Context 的根节点**，比如这里的 <font color="red">cxt 就是从父 Context 拷贝过来的可撤销的子 Context</font>
### 子协程达到一定条件，调用闭包里的取消CancelFunc，<font color="red">从而取消主协程的阻塞</font>
- 子协程参数为：匿名闭包（函数里会调用取消CancelFunc）， 也可以直接传参数（f context.CancelFunc，后面执行f()）
``` go 
package main

import (
    "context"
    "fmt"
    "sync/atomic"
    "time"
)

func AddNum(a *int32, b int, deferFunc func())  {
    defer func() {
        deferFunc()
    }()
    // 循环 原子操作成功 跳出break跳出循环，使用传入的匿名函数
    for i := 0; ; i++ {
        curNum := atomic.LoadInt32(a)
        newNum := curNum + 1
        time.Sleep(time.Millisecond * 200)
        // cas
        if atomic.CompareAndSwapInt32(a, curNum, newNum) {
            fmt.Printf("number当前值: %d [%d-%d]\n", *a, b, i)
            break
        } else {
            //fmt.Printf("The CAS operation failed. [%d-%d]\n", b, i)
        }
    }
}

func main() {
    total := 10
    var num int32
    fmt.Printf("number初始值: %d\n", num)
    fmt.Println("启动子协程...")
    ctx, cancelFunc := context.WithCancel(context.Background())
    for i := 0; i < total; i++ {
        // 闭包 因为匿名里 传递使用了cancelFunc
        go AddNum(&num, i, func() {
            // 每个协程的兜底判断 符合就关闭上下文
            if atomic.LoadInt32(&num) == int32(total) {
                cancelFunc()
            }
        })
    }
    // 阻塞 等待上下文关闭
    <- ctx.Done()
    fmt.Println("所有子协程执行完毕.")
}
```

### 主协程达到一定条件，调用取消CancelFunc，<font color="red">从而取消所有子协程（子协程select监听）</font>
``` go 
func subWorker(ctx context.Context) {
    for {
        select {
        case <-ctx.Done():
            fmt.Println("Subworker got canceled")
            return
        default:
            fmt.Println("Subworker is working")
            time.Sleep(time.Second)
        }
    }
}

func main() {
    parentCtx := context.Background()
    ctx, cancel := context.WithCancel(parentCtx)

    go subWorker(ctx)

    // 主协程中取消子协程
    time.Sleep(3 * time.Second)
    cancel()
    time.Sleep(1 * time.Second)
}
```
``` go 
// ExecuteRecord 执行任务计划
func (t *PromotionMaterialClearRecordCase) ExecuteRecord(ctx context.Context, xxxx) error {

    gCtx, cancel := context.WithCancel(ctx)
	defer cancel()
    // 启用信号量监听中断 先处理自定义事件
	sig := make(chan os.Signal)
	signal.Notify(sig, syscall.SIGINT, syscall.SIGQUIT, syscall.SIGTERM, syscall.SIGHUP)
	go func(ctx context.Context) {
		// 用range去取信号量通道的值 监听信号 阻塞且循环 		for { s := <-sig .....}
		for s := range sig {
			// 每次取信号量前判断下程序是否结束了
			select {
			case <-ctx.Done(): // 接收取消通知
				return // 结束
			default:
				switch s {
				// 非自然退出时
				case syscall.SIGINT, syscall.SIGQUIT, syscall.SIGTERM, syscall.SIGHUP:
					// 调用自己退出处理函数
					if i, ok := s.(syscall.Signal); ok {
						// 如果只是单纯打印 并没有os.Exit 还是会执行外面的 defer
						log.Context(ctx).Errorf("[ExecuteRecord] 程序非自然退出 捕捉信号量#%d, 主任务%d, 计划%d", int(i), recordInfo.TaskID, recordInfo.ID)
						executeStatus = 4
					}
				}
			}
		}
	}(gCtx)

    // 后续代码执行，如果不设置gctx,且子协程里一直在循环，就会导致协程未被释放
}
``` 
### 控制超时时间和携带信息
``` go 
// 超时控制
ctx, cancelFunc := context.WithTimeout(context.Background(), 10 * time.Second)
// 再封装了一层 返回子context
valueCtx := context.WithValue(ctx, "key", "value")
defer cancelFunc() // 思考这里为什么调用cancelFunc
for i := 0; i < total; i++ {
    // 子协程里也会调用的
    go AddNum(&num, i, func() {
        if atomic.LoadInt32(&num) == int32(total) {
            fmt.Println("key:", valueCtx.Value("key"))
            cancelFunc() // 处于ctx
        }
    })
}
// 用的是ctx
<- ctx.Done()

``` 
### <font color="red">为什么defer cancelFunc()</font>
- 多次调用cancelFunc,不会怎么样.调用cancelFunc时，底层调用cancel函数，函数中会判断当前上下文是否已经结束，如果已经结束了则直接return
- 主动调用cancelFunc是一个好习惯！**在函数结束后没有主动取消上下文，这会造成上下文泄露**
``` go
func main() {
    parent := context.Background()
    for i := 0; i < 100; i++ {
        go doRequest(parent)
    }
    time.Sleep(time.Second * 10)
}

// doRequest 模拟网络请求
func doRequest(parent context.Context) {
    // 超时控制 自动调用cancelFunc
    ctx, _ := context.WithTimeout(parent, time.Second*5) // 5秒超时的上下文
    // ctx, cancelFunc :=  context.WithTimeout(parent, time.Second*5)
    // defer cancelFunc() // 这样函数结束前 兜底释放
    time.Sleep(time.Millisecond * 200) // 模拟调用时长为200ms 函数就结束
    go func() {
        <-ctx.Done()
        fmt.Println("ctx done!")
    }()
}
``` 
在main函数中异步调用doRequest函数，doRequest函数中新建一个5s超时的上下文，doRequest函数的调用时长为200ms
**<font color="red">doRequest的上下文时间范围远大于函数调用花费的时间，在函数结束后没有主动取消上下文，这会造成上下文泄露</font>**

# <font color="red">源码阅读</font>
{{< innerlink src="posts/tech/go27.md" >}}

# 踩坑错误
- 超时的话显示的是 deadline exceeded
- 在代码中某处主动cancel的,报 context canceled 
因为其他协程超时，这个被动的cancel了 . 很大原因用了协程，然后协程传递了 任务方法的 ctx 进去。外面的程序执行的够快, 结束后里面新起的协程直接通过ctx上下文cancel了
  - 如果给 ctx 增加超时时间是没用的，因为给 ctx 设置超时时间的时候，它会和 parent context 的超时时间做对比
如果时间比 parent 的 时间长，那会取 parent 的时间
  - go 1.20以后 使用copy 重点使用了 context.WithoutCancel 方法该方法会保留所有 ctx 的信息，除了超时时间 (自己封装safego包里有处理 go 1.20 以前的兼容GoDetached方法)

``` go
package util

import (
    "context"
    "fmt"
    "runtime/debug"
    "time"
    "github.com/go-kratos/kratos/v2/log"
)

// SafeGo 安全执行协程函数，避免由于协程函数panic导致程序退出
// 协程 panic 时将在 命令行打印错误信息 并 记录到日志文件中
func SafeGo(ctx context.Context, fn func(ctx context.Context)) {
    go func(ctx context.Context) {
       defer func() {
          if err := recover(); err != nil {
             msg := fmt.Sprintf("执行协程函数panic, err:%+v, stacktrace:\n%s", err, string(debug.Stack()))
             fmt.Println(msg)
             log.Context(ctx).Errorf(msg)
          }
       }()
       fn(ctx)
    }(ctx)
}

// go 1.20 context.WithoutCancel
// SafeGoWithTimeout 安全执行协程函数，避免由于协程函数panic导致程序退出，timeout 不继承 ctx的超时时间，可以放心的在子协程中调用。
// 协程 panic 时将在 命令行打印错误信息 并 记录到日志文件中。
func SafeGoWithTimeout(ctx context.Context, timeout time.Duration, fn func(ctx context.Context)) {
    go func(ctx context.Context, cancel context.CancelFunc) {
       defer func() {
          if err := recover(); err != nil {
             msg := fmt.Sprintf("执行协程函数panic, err:%+v, stacktrace:\n%s", err, string(debug.Stack()))
             fmt.Println(msg)
             log.Context(ctx).Errorf(msg)
          }
          cancel()
       }()
       fn(ctx)
    }(context.WithTimeout(context.WithoutCancel(ctx), timeout))
}

```